#!/bin/bash
declare FILE=docker-compose.yml

main() {
  case $1 in
    rspec)
      rspec ${@:2}
    ;;
    logs)
      logs ${@:2}
    ;;
    run)
      run ${@:2}
    ;;
    "exec")
      dce ${@:2}
    ;;
    ps)
      ps
    ;;
    stop)
      stop ${@:2}
    ;;
    kill)
      kill ${@:2}
    ;;
    install)
      install
    ;;
    uninstall)
      uninstall
    ;;
    help|-h)
      help
    ;;
    -t)
      FILE=docker-compose-test.yml
      main ${@:2}
    ;;
    *)
      dc $@
    ;;
  esac
}

dc() {
  docker-compose -f $FILE $@
}

dcd() {
  docker-compose -f docker-compose.yml $@
}

dct() {
  docker-compose -f docker-compose-test.yml $@
}

dce() {
  local cont=$(find_container "dc ps" $1)
  local cmd=$(find_command)
  echo 'docker exec -it '$cont $cmd
  docker exec -it $cont $cmd
}

find_command() {
  local cmd=$1
  if [ -z $cmd ]; then
    echo 'bash'
  else
    echo $@
  fi
}

find_container() {
  local cont=$($1 | grep $2)
  cont=${cont/%\ */}
  echo $cont
}

rspec() {
  if [ "$1" == "-k" ]; then
    dct run --name test_runner server bash
    dce test_runner bundle exec rspec ${@:2}
  else
    dct run server bundle exec rspec $@
  fi
}

logs() {
  case $1 in
    "")
      dc logs -f --tail=100 server
    ;;
    all)
      dc logs -f --tail=100
    ;;
    clear)
      logs_clear ${@:2}
    ;;
    *)
      dc logs -f --tail=100 $@
    ;;
  esac
}

logs_clear() {
  if [ -z $@ ]; then
    echo "Need to inform a container, use:"
    echo "${0##*/} logs clear <container name>"
  else
    echo "Clear logs from [$@]"
    for container in $@; do
      logs_clear_compose $container
    done
  fi
}

logs_clear_compose() {
  local cont=$(dc ps | grep $1)
  cont=${cont/%\ */}
  clear_logs_from_container $cont
}

clear_logs_from_container() {
  sudo rm $(docker inspect $1 | grep -G '"LogPath": "*"' | sed -e 's/.*"LogPath": "//g' | sed -e 's/",//g');
}

run() {
  case $1 in
    "")
      dc run server bash
    ;;
    *)
      dc run $1 bash ${@:2}
    ;;
  esac
}

ps() {
  dcd ps
  dct ps
}

stop() {
  dcd stop $@
  dct stop $@
}

kill() {
  dcd kill $@
  dct kill $@
}

install() {
  sudo cp $0 /usr/bin
}

uninstall(){
  sudo rm $0
}

help() {
  echo "help"
}

main $@
