#!/bin/bash
ruby_main() {
  case $1 in
    rspec)
      rspec ${@:2}
    ;;
    bundle)
      dc run $2 bundle ${@:3}
    ;;
    bexec)
      dc run $2 bundle exec ${@:3}
    ;;
    rake)
      dc run $2 bundle exec rake ${@:3}
    ;;
    kill)
      rspec rm
    ;;
    help|-h)
      ruby_help
    ;;
  esac
}

rspec() {
  case $1 in
    up)
      dct run --rm --name $(test_runner) $TEST_CONTAINER bash
    ;;
    rm)
      # local cont="$(find_container $(test_runner))"
      my_exec docker stop $(test_runner) >/dev/null 2>&1
      my_exec docker rm $(test_runner) >/dev/null 2>&1
    ;;
    *)
      local cont="$(find_container $(test_runner))"
      if [ "$(is_running $cont)" == "true" ]; then
        dce $(test_runner) bundle exec rspec $@
      else
        dct run $TEST_CONTAINER bundle exec rspec $@
      fi
    ;;
  esac
}

ruby_help() {
  cat <<-TEXT
Ruby-Helpers:
  rspec <command>                 docker-compose -f $test_file run $test_container bundle exec rspec <command>
  bundle <container> <command>    docker-compose run <container> bundle <command>
  bexec <container> <command>     docker-compose run <container> bundle exec <command>
  rake <container> <command>      docker-compose run <container> bundle exec rake <command>
TEXT
}

# loadfile
# source lima
# main $@
